services:
  server:
    image: gitea/gitea:1.23.4
    restart: always
    volumes:
      - ./config:/data/gitea/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host